language: go

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

os: linux

go:
  - "1.14"

install: skip

env:
  global:
    - KUBEBUILDER_VERSION=2.3.0
    - GOLANGCI_LINT_VERSION=1.25.0
    - KUSTOMIZE_VERSION=3.5.4
    - KIND_VERSION=0.7.0
  jobs:
    - K8S_VERSION=1.15.7
    - K8S_VERSION=1.16.4
    - K8S_VERSION=1.17.2
    - K8S_VERSION=1.18.0

services:
  - docker

before_script:
  - sudo install -d /usr/local/kubebuilder -o $(id -u) -g $(id -g)
  - curl -L https://go.kubebuilder.io/dl/${KUBEBUILDER_VERSION}/$(go env GOOS)/$(go env GOARCH) | tar --strip-components=1 -xz -C /usr/local/kubebuilder
  - export PATH=$PATH:/usr/local/kubebuilder/bin
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v${GOLANGCI_LINT_VERSION}
  - echo "$QUAY_TOKEN" | docker login -u "$QUAY_USER" --password-stdin quay.io
  - curl -sSfL https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_amd64.tar.gz | sudo tar -xz -C /usr/local/bin

script:
  - make test
  - make lint
  - DEBUG=true make e2e-test
