language: go

cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

os: linux

go:
  - "1.13"

install: skip

env:
  global:
    - KUBEBUILDER_VERSION=2.2.0
    - GOLANGCI_LINT_VERSION=1.23.6
  jobs:
    - K8S_VERSION=1.15.7
    - K8S_VERSION=1.16.4
    - K8S_VERSION=1.17.2

services:
  - docker

before_script:
  - sudo install -d /usr/local/kubebuilder -o $(id -u) -g $(id -g)
  - curl -L https://go.kubebuilder.io/dl/${KUBEBUILDER_VERSION}/$(go env GOOS)/$(go env GOARCH) | tar --strip-components=1 -xz -C /usr/local/kubebuilder
  - export PATH=$PATH:/usr/local/kubebuilder/bin
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v${GOLANGCI_LINT_VERSION}
  - echo "$QUAY_TOKEN" | docker login -u "$QUAY_USER" --password-stdin quay.io
  - (cd /usr/local/bin && curl -sSfL "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | sudo bash)

script:
  - make test
  - make lint
  - make e2e-test
